module.exports = {
  BRANCHES: "branches",
  EXPERIENCES: "experiences",
  CAREERMOBILITIES: "careerMobilities",
  COMPETENCIES: "competencies",
  DEPARTMENTS: "departments",
  DIPLOMAS: "diplomas",
  DIRECTORATES: "directorates",
  DIVISIONS: "divisions",
  EDUCATION: "education",
  TENURES: "tenures",
  GROUPLEVELS: "groupLevels",
  KEYCOMPETENCIES: "keyCompetencies",
  ORGANIZATIONS: "organizations",
  SCHOOLS: "schools",
  SECONDLANGUAGEPROFICIENCIES: "secondLanguageProficiencies",
  SECTORS: "sectors",
  SECURITYCLEARANCES: "securityClearances",
  SKILLS: "skills",
  TALENTMATRIXRESULTS: "talentMatrixResults",
  USERCOMPETENCIES: "userCompetencies",
  USERDEVELOPMENTALGoALS: "userDevelopmentalGoals",
  USER_ORGANIZATIONS: "user_organizations",
  USERPROJECTS: "userProjects",
  USERSKILLS: "userSkills",
  USERS: "users"
};
